from django.urls import path

from .views import (
    CustomerRegisterAPIView,
    CustomerLoginAPIView,
    CustomerDetailAPIView,
    AccountByCardAPIView,
    TransactionsByCardAPIView,
    CashInAPIView,
    CashOutAPIView,
    TransferAPIView,
    BilimZoneTopUpAPIView,
    PaymentAPIView,
    BilimZoneUserSyncAPIView,
    CardVerifyAPIView,
    CardConfirmAPIView,
    BankCustomerListAPIView,
    CustomerPendingCodesAPIView,
    BilimZonePurchaseView,
    BilimZoneCreatePurchaseCodeView,
    BilimZoneConfirmPurchaseCodeView,
    BilimZoneWalletCreateCodeView,
    BilimZoneWalletConfirmCodeView,
)

urlpatterns = [
    path(
        "customers/",
        BankCustomerListAPIView.as_view(),
        name="bank-customer-list",
    ),
    path(
        "customers/register/",
        CustomerRegisterAPIView.as_view(),
        name="bank-customer-register",
    ),
    path(
        "customers/login/",
        CustomerLoginAPIView.as_view(),
        name="bank-customer-login",
    ),
    path(
        "customers/<int:customer_id>/",
        CustomerDetailAPIView.as_view(),
        name="bank-customer-detail",
    ),
    path(
        "customers/<int:customer_id>/codes/",
        CustomerPendingCodesAPIView.as_view(),
        name="bank-customer-codes",
    ),
    path(
        "accounts/card/<str:card_number>/",
        AccountByCardAPIView.as_view(),
        name="bank-account-by-card",
    ),
    path(
        "accounts/card/<str:card_number>/transactions/",
        TransactionsByCardAPIView.as_view(),
        name="bank-card-transactions",
    ),
    path(
        "card/verify/",
        CardVerifyAPIView.as_view(),
        name="bank-card-verify",
    ),
    path(
        "card/confirm/",
        CardConfirmAPIView.as_view(),
        name="bank-card-confirm",
    ),
    path(
        "cash-in/",
        CashInAPIView.as_view(),
        name="bank-cash-in",
    ),
    path(
        "cash-out/",
        CashOutAPIView.as_view(),
        name="bank-cash-out",
    ),
    path(
        "transfer/",
        TransferAPIView.as_view(),
        name="bank-transfer",
    ),
    path(
        "bilimzone/sync-user/",
        BilimZoneUserSyncAPIView.as_view(),
        name="bank-bilimzone-sync-user",
    ),
    path(
        "bilimzone/top-up/",
        BilimZoneTopUpAPIView.as_view(),
        name="bank-bilimzone-top-up",
    ),
    path(
        "bilimzone/purchase/",
        BilimZonePurchaseView.as_view(),
        name="bank-bilimzone-purchase",
    ),
    path(
        "pay/",
        PaymentAPIView.as_view(),
        name="bank-payment",
    ),
    path(
        "bilimzone/purchase/create-code/",
        BilimZoneCreatePurchaseCodeView.as_view(),
        name="bank-bilimzone-purchase-create-code",
    ),
    path(
        "bilimzone/purchase/confirm-code/",
        BilimZoneConfirmPurchaseCodeView.as_view(),
        name="bank-bilimzone-purchase-confirm-code",
    ),
    path(
        "bilimzone/wallet/create-code/",
        BilimZoneWalletCreateCodeView.as_view(),
        name="bank-bilimzone-wallet-create-code",
    ),
    path(
        "bilimzone/wallet/confirm-code/",
        BilimZoneWalletConfirmCodeView.as_view(),
        name="bank-bilimzone-wallet-confirm-code",
    ),
]
