# Generated by Django 4.2.30 on 2026-05-04 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        ("users", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgreementTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("all", "All users"),
                            ("author", "Author"),
                            ("organization", "Organization"),
                            ("author_organization", "Author and Organization"),
                        ],
                        default="all",
                        max_length=50,
                    ),
                ),
                (
                    "context",
                    models.CharField(
                        choices=[
                            ("registration", "Registration"),
                            ("paid_material", "Paid material"),
                            ("publication", "Material publication"),
                            ("all", "All contexts"),
                        ],
                        default="registration",
                        max_length=50,
                    ),
                ),
                ("text", models.TextField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="agreements/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="materials/"),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True, null=True, upload_to="material_covers/"
                    ),
                ),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("published", "Published"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("reject_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="users.user",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="materials",
                        to="categories.catalogcategory",
                    ),
                ),
            ],
        ),
    ]
