# Generated by Django 4.2.30 on 2026-05-04 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "__first__"),
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_ru", models.CharField(max_length=255)),
                ("name_kg", models.CharField(blank=True, max_length=255, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="material",
            name="is_paid",
        ),
        migrations.RemoveField(
            model_name="material",
            name="price",
        ),
        migrations.AlterField(
            model_name="agreementtemplate",
            name="audience",
            field=models.CharField(
                choices=[
                    ("all", "Все пользователи"),
                    ("author", "Автор"),
                    ("organization", "Организация"),
                    ("author_organization", "Автор и организация"),
                ],
                default="all",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="agreementtemplate",
            name="context",
            field=models.CharField(
                choices=[
                    ("registration", "Регистрация"),
                    ("paid_material", "Платный материал"),
                    ("publication", "Публикация материала"),
                    ("all", "Везде"),
                ],
                default="registration",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="author_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.user"
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("pending", "На проверке"),
                    ("published", "Опубликован"),
                    ("rejected", "Отклонён"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="CategoryOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label_ru",
                    models.CharField(default="Выберите класс", max_length=255),
                ),
                ("label_kg", models.CharField(blank=True, max_length=255, null=True)),
                ("value", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="admin_panel.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CategoryDirection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_ru", models.CharField(max_length=255)),
                ("name_kg", models.CharField(blank=True, max_length=255, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="directions",
                        to="admin_panel.category",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="material",
            name="direction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="admin_panel.categorydirection",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="admin_panel.category",
            ),
        ),
    ]
