# Generated by Django 4.2.30 on 2026-05-27 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_wallet"),
        ("admin_panel", "0003_platform_commission"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agreementtemplate",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="agreementtemplate",
            name="audience",
            field=models.CharField(
                choices=[
                    ("all", "Все пользователи"),
                    ("reader", "Читатель"),
                    ("author", "Автор"),
                    ("organization", "Организация"),
                    ("author_organization", "Автор и организация"),
                ],
                default="all",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="UserAgreementAcceptance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audience", models.CharField(max_length=50)),
                ("context", models.CharField(max_length=50)),
                ("accepted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acceptances",
                        to="admin_panel.agreementtemplate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agreement_acceptances",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "ordering": ["-accepted_at"],
            },
        ),
    ]
