# Generated by Django 4.2.30 on 2026-05-28 04:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0004_alter_agreementtemplate_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Material",
        ),
    ]
