# Generated by Django 3.2.25 on 2026-05-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('material_request', 'Запрос на публикацию'), ('material_published', 'Материал опубликован'), ('material_rejected', 'Материал отклонён'), ('material_purchase', 'Покупка материала'), ('system_income', 'Доход системы'), ('purchase_success', 'Успешная покупка'), ('general', 'Общее')], default='general', max_length=50),
        ),
    ]
