# Generated by Django 4.2.30 on 2026-05-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="catalogitem",
            name="category",
        ),
        migrations.AlterModelOptions(
            name="catalogcategory",
            options={},
        ),
        migrations.RemoveField(
            model_name="catalogcategory",
            name="sort_order",
        ),
        migrations.AddField(
            model_name="catalogcategory",
            name="description_kg",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="catalogcategory",
            name="description_ru",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="CatalogExtraOption",
        ),
        migrations.DeleteModel(
            name="CatalogItem",
        ),
    ]
