# Generated by Django 4.2.30 on 2026-05-04 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0003_alter_catalogcategory_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogClassOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.RemoveField(
            model_name="catalogcategory",
            name="extra_label_kg",
        ),
        migrations.RemoveField(
            model_name="catalogcategory",
            name="extra_label_ru",
        ),
        migrations.DeleteModel(
            name="CatalogExtraOption",
        ),
        migrations.AddField(
            model_name="catalogclassoption",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_options",
                to="categories.catalogcategory",
            ),
        ),
    ]
