# Generated by Django 4.2.30 on 2026-05-17 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "__first__"),
        ("admin_panel", "0002_category_remove_material_is_paid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "publication_type",
                    models.CharField(
                        choices=[
                            ("book", "Книга"),
                            ("article", "Научная статья"),
                            ("coursework", "Курсовая работа"),
                            ("diploma", "Дипломная работа"),
                            ("lecture", "Лекция / конспект"),
                            ("methodical", "Методическое пособие"),
                            ("test", "Тест"),
                            ("other", "Другое"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "price_type",
                    models.CharField(
                        choices=[("free", "Бесплатно"), ("paid", "Платно")],
                        default="free",
                        max_length=50,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="publications/files/"
                    ),
                ),
                (
                    "preview_file",
                    models.FileField(
                        blank=True, null=True, upload_to="publications/previews/"
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, null=True, upload_to="publications/pdf/"
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True, null=True, upload_to="publications/covers/"
                    ),
                ),
                ("preview_start_page", models.PositiveIntegerField(default=1)),
                ("preview_end_page", models.PositiveIntegerField(default=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("pending", "На проверке"),
                            ("published", "Опубликован"),
                            ("rejected", "Отклонён"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("reject_reason", models.TextField(blank=True, null=True)),
                ("agreement_accepted", models.BooleanField(default=False)),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("downloads_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publications",
                        to="users.user",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="publications",
                        to="admin_panel.category",
                    ),
                ),
                (
                    "direction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="publications",
                        to="admin_panel.categorydirection",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="publications",
                        to="admin_panel.categoryoption",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PublicationReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField()),
                ("text", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="publications.publication",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publication_reviews",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("publication", "user")},
            },
        ),
    ]
