# Generated by Django 4.2.30 on 2026-05-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="cover_page_number",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="publication",
            name="file_sha256",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="publication",
            name="cover",
            field=models.FileField(
                blank=True, null=True, upload_to="publications/covers/"
            ),
        ),
    ]
