# Generated by Django 4.2.30 on 2026-05-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0002_publication_cover_page_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="cover",
            field=models.ImageField(
                blank=True, null=True, upload_to="publications/covers/"
            ),
        ),
    ]
