# Generated by Django 4.2.30 on 2026-05-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0003_alter_publication_cover"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="extracted_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="publication",
            name="similarity_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="publication",
            name="text_sha256",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
