# Generated by Django 4.2.30 on 2026-05-28 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0004_publication_extracted_text_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicationSimilarityMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("duplicate_file", "Дубликат файла"),
                            ("duplicate_text", "Дубликат текста"),
                            ("similar_text_warning", "Похожий текст"),
                        ],
                        max_length=50,
                    ),
                ),
                ("similarity_percent", models.PositiveIntegerField(default=0)),
                (
                    "matched_status",
                    models.CharField(default="published", max_length=50),
                ),
                ("detail", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "matched_publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matched_similarity_publications",
                        to="publications.publication",
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarity_matches",
                        to="publications.publication",
                    ),
                ),
            ],
            options={
                "ordering": ["-similarity_percent", "-created_at"],
                "unique_together": {
                    ("publication", "matched_publication", "match_type")
                },
            },
        ),
    ]
