# Generated by Django 4.2.30 on 2026-05-17 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("publications", "0001_initial"),
        ("users", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicationPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "owner_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "system_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("bank_response", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publication_purchases",
                        to="users.user",
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="publications.publication",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("buyer", "publication")},
            },
        ),
    ]
