# Generated by Django 3.2.25 on 2026-05-11 14:49

import bank.models
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(default=bank.models.generate_iban, max_length=30, unique=True)),
                ('currency', models.CharField(default='KGS', max_length=3)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('external_bilimzone_user_id', models.CharField(blank=True, help_text='ID пользователя в BilimZone, если банк привязан к аккаунту BilimZone', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('transaction_type', models.CharField(choices=[('INITIAL', 'Начальный баланс'), ('CASH_IN', 'Пополнение'), ('CASH_OUT', 'Снятие'), ('TRANSFER_IN', 'Входящий перевод'), ('TRANSFER_OUT', 'Исходящий перевод'), ('BILIMZONE_TOP_UP', 'Пополнение BilimZone'), ('PAYMENT', 'Оплата')], max_length=40)),
                ('status', models.CharField(choices=[('SUCCESS', 'Успешно'), ('FAILED', 'Ошибка')], default='SUCCESS', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='KGS', max_length=3)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('external_service', models.CharField(blank=True, max_length=100)),
                ('external_user_id', models.CharField(blank=True, max_length=100)),
                ('external_reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bank.bankaccount')),
                ('target_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transactions', to='bank.bankaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(default=bank.models.generate_card_number, max_length=16, unique=True)),
                ('card_holder', models.CharField(max_length=255)),
                ('expiry_month', models.PositiveSmallIntegerField(default=12)),
                ('expiry_year', models.PositiveSmallIntegerField(default=2030)),
                ('cvv', models.CharField(default='111', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='bank.bankaccount')),
            ],
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='bank.bankcustomer'),
        ),
    ]
