# Generated by Django 3.2.25 on 2026-05-12 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcustomer',
            name='external_bilimzone_user_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID пользователя в BilimZone', max_length=100),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('INITIAL', 'Начальный баланс'), ('CASH_IN', 'Пополнение'), ('CASH_OUT', 'Снятие'), ('TRANSFER_IN', 'Входящий перевод'), ('TRANSFER_OUT', 'Исходящий перевод'), ('BILIMZONE_TOP_UP', 'Пополнение BilimZone'), ('PAYMENT', 'Оплата'), ('INCOME', 'Доход владельца'), ('COMMISSION', 'Комиссия системы')], max_length=40),
        ),
    ]
