# Generated by Django 3.2.25 on 2026-05-21 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20260512_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankConfirmationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('PURCHASE', 'Покупка BilimZone'), ('TOP_UP', 'Пополнение BilimZone')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает подтверждения'), ('USED', 'Использован'), ('EXPIRED', 'Истёк')], default='PENDING', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='KGS', max_length=3)),
                ('external_reference', models.CharField(db_index=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation_codes', to='bank.bankcustomer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
